### PR TITLE
Detecting + removing orphaned credentials

### PR DESCRIPTION
**Pull request by techsmyth**
Updated script and associated graphql files for detecting and removing orphaned credentials.

### CODE REVIEW

**Comment by Comoque1** [comment]
@techsmyth, could you please resolve the conflicts?
image

**Comment by Comoque1** [comment]
@techsmyth, I've triggered the script against acc env, where we have some data.
The result was that there are 48 orphaned credentials for users against, hub / challenge / opportunity.

After digging deeper into the data, it appears, that the script identifies, credentials as orphaned, when the hub is demo or archived, which doesn't seem right.
image
image

**Comment by techsmyth** [comment]
@Comoque1 very important catch, this can be easily fixed.

**Comment by techsmyth** [comment]
@Comoque1 please try it now...I sent up a commit to also retrieve DEMO + ARCHIVE hubs

**Comment by Comoque1** [comment]
Checked couple of the returned IDs for Hubs, Challenges and Opportunities (after the fix) against PROD db and such data doesn't exist anymore.

**Review by Comoque1 — APPROVED** [review]

**Pull request merged**
